using System;

namespace yocar.Districts
{
    public class District : DistrictBase
    {
        //<suite-custom-code-autogenerated>
        protected District()
        {

        }

        public District(Guid id, Guid provinceCityId, string name, string slug, string description)
            : base(id, provinceCityId, name, slug, description)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}