using System;

namespace yocar.Wards
{
    public class Ward : WardBase
    {
        //<suite-custom-code-autogenerated>
        protected Ward()
        {

        }

        public Ward(Guid id, Guid districtId, string name, string description, string slug)
            : base(id, districtId, name, description, slug)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}