using System;

namespace yocar.ProvinceCities
{
    public class ProvinceCity : ProvinceCityBase
    {
        //<suite-custom-code-autogenerated>
        protected ProvinceCity()
        {

        }

        public ProvinceCity(Guid id, string name, string slug, string description)
            : base(id, name, slug, description)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}